server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}/neondb?sslmode=require
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update  # Change to 'validate' or 'none' in production
    show-sql: true  # Logs SQL queries (optional)